workflows:
  vite_capacitor_build:
    name: MyFocus
    environment:
      node: 20
      vars:
        PACKAGE_NAME: "app.accs.tofo"
    scripts:
      - echo "📦 Installing dependencies..."
      - npm install

      - echo "🔧 Building the Vite app..."
      - npm run build

      - echo "➕ Adding Android platform (if not already added)..."
      - if [ ! -d "android" ]; then npx cap add android; fi

      - echo "🔄 Syncing Capacitor with Android..."
      - npx cap sync android

      - echo "📥 Installing Gradle manually..."
      - |
        GRADLE_VERSION=8.7
        wget https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip
        unzip gradle-${GRADLE_VERSION}-bin.zip -d gradle
        export GRADLE_HOME=$PWD/gradle/gradle-${GRADLE_VERSION}
        export PATH=$GRADLE_HOME/bin:$PATH
        gradle -v

      - echo "🏗️ Building APK..."
      - cd android
      - gradle assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
