workflows:
  vite_capacitor_build:
    name: MyFocus
    environment:
      node: 20
      java: 21
      vars:
        PACKAGE_NAME: "app.accs.tofo"
    scripts:
      - |
        echo "📦 Installing NPM dependencies..."
        npm install

      - |
        echo "🔧 Building the Vite frontend..."
        npm run build

      - |
        echo "➕ Adding Android platform if not present..."
        if [ ! -d "android" ]; then npx cap add android; fi

      - |
        echo "🔄 Syncing Capacitor with Android..."
        npx cap sync android

      - |
        echo "📥 Checking/Installing Gradle wrapper (if missing)..."
        if [ ! -f "./android/gradlew" ]; then
          cd android
          gradle wrapper
          cd ..
        fi

      - |
        echo "✅ Giving executable permission to gradlew..."
        chmod +x android/gradlew

      - |
        echo "🏗️ Building APK..."
        cd android && ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.apk
