workflows:
  vite_capacitor_build:
    name: MyFocus
    environment:
      node: 20
      java: 21
      vars:
        PACKAGE_NAME: "app.accs.tofo"
    scripts:
      - |
        echo "📦 Installing NPM dependencies..."
        npm install

      - |
        echo "🔧 Building Vite app..."
        npm run build

      - |
        echo "➕ Adding Android platform if not already added..."
        if [ ! -d "android" ]; then npx cap add android; fi

      - |
        echo "🔄 Syncing Capacitor with Android..."
        npx cap sync android

      - |
        echo "📥 Ensuring Gradle wrapper exists..."
        if [ ! -f "android/gradlew" ]; then
          cd android
          gradle wrapper
          cd ..
        fi

      - |
        echo "✅ Fixing permissions for gradlew..."
        chmod +x android/gradlew

      - |
        echo "🛠️ Cleaning bad JVM options if set..."
        unset DEFAULT_JVM_OPTS

      - |
        echo "🏗️ Building APK..."
        cd android && ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.apk
