workflows:
  vite_capacitor_build:
    name: MyFocus
    environment:
      node: 20
      java: 21
      vars:
        PACKAGE_NAME: "app.accs.tofo"
    scripts:
      - |
        echo "📦 Installing NPM dependencies..."
        npm install

      - |
        echo "🔧 Building the Vite frontend..."
        npm run build

      - |
        echo "➕ Adding Android platform if not present..."
        if [ ! -d "android" ]; then npx cap add android; fi

      - |
        echo "🔄 Syncing Capacitor..."
        npx cap sync android

      - |
        echo "📥 Checking/Installing Gradle manually (if missing)..."
        if [ ! -f "./android/gradlew" ]; then
          echo "⚠️ Gradle wrapper missing. Initializing..."
          cd android
          gradle wrapper
          cd ..
        fi

      - |
        echo "🏗️ Building APK..."
        cd android && ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.apk
