workflows:
  vite_capacitor_build:
    name: MyFocus Android Build
    environment:
      node: 20
    scripts:
      - echo "📦 Installing dependencies…"
      - npm install

      - echo "🔧 Building Vite frontend…"
      - npm run build

      - echo "➕ Adding Android platform if missing…"
      - if [ ! -d "./android" ]; then npx cap add android; fi

      - echo "🔄 Syncing Capacitor platform…"
      - npx cap sync android

      - echo "📥 Setting up Gradle"
      - cd android
      - |
        GRADLE_VERSION=8.7
        wget https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip
        unzip gradle-${GRADLE_VERSION}-bin.zip -d gradle
        export PATH=$PWD/gradle/gradle-${GRADLE_VERSION}/bin:$PATH
        gradle -v

      - echo "🏗 Assembling Debug APK"
      - gradle assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.apk
